apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  selector:
    app: thanos-query
  type: LoadBalancer
  ports:
  - name: http
    port: 9090
    targetPort: http
