apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-receiver
data:
  # endpoints should be adjusted as the number of thanos-receiver replicas is changed
  hashring.json: |
    [
      {
        "endpoints": [
          "thanos-receiver-0.thanos-receiver:10901",
          "thanos-receiver-1.thanos-receiver:10901"
        ]
      }
    ]