apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver
  labels:
    app: thanos-receiver
spec:
  clusterIP: None
  selector:
    app: thanos-receiver
  ports:
  # StoreAPI grpc
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 10902
    targetPort: http