apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: thanos-receiver
  name: thanos-receiver
spec:
  replicas: 2
  serviceName: thanos-receiver
  selector:
    matchLabels:
      app: thanos-receiver
  template:
    metadata:
      labels:
        app: thanos-receiver
    spec:
      containers:
        - image: quay.io/thanos/thanos:v0.13.0
          name: thanos-receiver
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - receive
            - --log.level=debug
            - --tsdb.path=/data
            - --objstore.config-file=/etc/thanos/objstore/objstore-config.yaml
            - --receive.hashrings-file=/etc/thanos/receiver/hashring.json
            - --receive.local-endpoint=$(POD_NAME).thanos-receiver:10901
            - --tsdb.retention=6h
          volumeMounts:
            - mountPath: /etc/thanos/objstore/
              name: objstore-config
            - mountPath: /etc/thanos/receiver/
              name: receiver-config
            - mountPath: /data
              name: data
          ports:
            - containerPort: 10901
              name: grpc
            - containerPort: 10902
              name: http
            - containerPort: 19291
              name: write
      volumes:
        - name: objstore-config
          secret:
            secretName: thanos-objstore-config
            items:
              - key: thanos-objstore-config.yaml
                path: objstore-config.yaml
        - name: receiver-config
          configMap:
            name: thanos-receiver
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi