apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver-ext
  labels:
    app: thanos-receiver
spec:
  selector:
    app: thanos-receiver
  type: LoadBalancer
  ports:
  # Prometheus remote-write http
  - name: write
    port: 19291
    targetPort: write